services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nfse
      POSTGRES_PASSWORD: nfse
      POSTGRES_DB: nfse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
