"""clientes e vinculo com emissao

Revision ID: 21e3b103dfb0
Revises: acb1fefcc7f5
Create Date: 2026-08-13 14:29:08.263773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e3b103dfb0'
down_revision: Union[str, Sequence[str], None] = 'acb1fefcc7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=True),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('eh_padrao_csv', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clientes_empresa_cpf_cnpj', 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True, postgresql_where=sa.text('cpf_cnpj IS NOT NULL'))
    op.create_index('ix_clientes_empresa_padrao_csv', 'clientes', ['empresa_id'], unique=True, postgresql_where=sa.text('eh_padrao_csv = true'))
    op.add_column('emissoes', sa.Column('cliente_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'emissoes', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emissoes', type_='foreignkey')
    op.drop_column('emissoes', 'cliente_id')
    op.drop_index('ix_clientes_empresa_padrao_csv', table_name='clientes', postgresql_where=sa.text('eh_padrao_csv = true'))
    op.drop_index('ix_clientes_empresa_cpf_cnpj', table_name='clientes', postgresql_where=sa.text('cpf_cnpj IS NOT NULL'))
    op.drop_table('clientes')
    # ### end Alembic commands ###
