"""cria empresas, usuarios, emissoes

Revision ID: 30a7badcb2c4
Revises: 
Create Date: 2026-08-11 14:19:25.380968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a7badcb2c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=False),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=False),
    sa.Column('op_simp_nac', sa.Integer(), nullable=False),
    sa.Column('codigo_tributacao', sa.String(length=6), nullable=False),
    sa.Column('descricao_servico_padrao', sa.String(length=2000), nullable=False),
    sa.Column('ambiente', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=False),
    sa.Column('proximo_numero', sa.Integer(), nullable=False),
    sa.Column('certificado_pfx_cifrado', sa.Text(), nullable=False),
    sa.Column('certificado_senha_cifrada', sa.Text(), nullable=True),
    sa.Column('certificado_valido_ate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('webhook_token_hash', sa.String(length=255), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emissoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('stone_charge_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('dps_id', sa.String(length=45), nullable=True),
    sa.Column('chave_acesso', sa.String(length=50), nullable=True),
    sa.Column('xml_dps', sa.LargeBinary(), nullable=True),
    sa.Column('xml_nfse', sa.LargeBinary(), nullable=True),
    sa.Column('erros', sa.Text(), nullable=True),
    sa.Column('tomador_cpf_cnpj', sa.String(length=14), nullable=True),
    sa.Column('tomador_nome', sa.String(length=300), nullable=True),
    sa.Column('tomador_email', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=2000), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('criada_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criada_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emissoes_empresa_stone_charge_id', 'emissoes', ['empresa_id', 'stone_charge_id'], unique=True, postgresql_where=sa.text('stone_charge_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emissoes_empresa_stone_charge_id', table_name='emissoes', postgresql_where=sa.text('stone_charge_id IS NOT NULL'))
    op.drop_table('emissoes')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
