"""cancelamento de nota

Revision ID: 6fc65ec86b40
Revises: 21e3b103dfb0
Create Date: 2026-08-13 14:38:35.328668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc65ec86b40'
down_revision: Union[str, Sequence[str], None] = '21e3b103dfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emissoes', sa.Column('motivo_cancelamento', sa.String(length=2000), nullable=True))
    op.add_column('emissoes', sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emissoes', 'cancelada_em')
    op.drop_column('emissoes', 'motivo_cancelamento')
    # ### end Alembic commands ###
