"""multiempresa e licenciamento

Revision ID: acb1fefcc7f5
Revises: 30a7badcb2c4
Create Date: 2026-08-13 07:23:33.471230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb1fefcc7f5'
down_revision: Union[str, Sequence[str], None] = '30a7badcb2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('limite_empresas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('plano_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aceito_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('usuario_empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', name='uq_usuario_empresa')
    )
    op.add_column('empresas', sa.Column('titular_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'usuarios', ['titular_id'], ['id'])
    op.add_column(
        'usuarios',
        sa.Column('eh_admin_plataforma', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('usuarios', sa.Column('plano_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('usuarios_empresa_id_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'planos', ['plano_id'], ['id'])
    # ### end Alembic commands ###

    # Backfill: para cada Usuario com empresa_id/papel preenchidos (modelo
    # antigo), cria o vinculo correspondente em usuario_empresas e, se
    # papel=admin, preenche empresas.titular_id (se a empresa ainda nao tiver
    # titular). Nao ha dados reais em producao ainda — isso e so para nao
    # quebrar ambientes de desenvolvimento/teste existentes.
    import uuid as _uuid
    from datetime import datetime as _datetime, timezone as _timezone

    conexao = op.get_bind()
    linhas = conexao.execute(
        sa.text("SELECT id, empresa_id, papel FROM usuarios WHERE empresa_id IS NOT NULL")
    ).fetchall()
    agora = _datetime.now(_timezone.utc)
    titulares_definidos: set = set()
    for usuario_id, empresa_id, papel in linhas:
        conexao.execute(
            sa.text(
                "INSERT INTO usuario_empresas (id, usuario_id, empresa_id, papel, criado_em) "
                "VALUES (:id, :usuario_id, :empresa_id, :papel, :criado_em)"
            ),
            {
                "id": _uuid.uuid4(), "usuario_id": usuario_id, "empresa_id": empresa_id,
                "papel": papel, "criado_em": agora,
            },
        )
        if papel == "admin" and empresa_id not in titulares_definidos:
            conexao.execute(
                sa.text(
                    "UPDATE empresas SET titular_id = :usuario_id "
                    "WHERE id = :empresa_id AND titular_id IS NULL"
                ),
                {"usuario_id": usuario_id, "empresa_id": empresa_id},
            )
            titulares_definidos.add(empresa_id)

    op.drop_column('usuarios', 'papel')
    op.drop_column('usuarios', 'empresa_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('papel', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_empresa_id_fkey'), 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('usuarios', 'plano_id')
    op.drop_column('usuarios', 'eh_admin_plataforma')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'titular_id')
    op.drop_table('usuario_empresas')
    op.drop_table('convites')
    op.drop_table('planos')
    # ### end Alembic commands ###
