// Fonte oficial: Portal Nacional da NF-e / NFS-e -- Informe Tecnico 2025.002
// (CST + cClassTrib, 28/09/2026) e Anexo VII - IndOp_IBSCBS v1.02.00 (codigo
// indicador de operacao, filtrado aos aplicaveis a NFS-e -- indNFSe=S).
// NAO EDITAR A MAO -- gerado a partir das planilhas oficiais do gov.br/nfse.

export interface CstIbsCbsItem { codigo: string; nome: string; }
export const CST_IBS_CBS: CstIbsCbsItem[] = [
  { codigo: "000", nome: "Tributação integral" },
  { codigo: "010", nome: "Tributação com alíquotas uniformes" },
  { codigo: "011", nome: "Tributação com alíquotas uniformes reduzidas" },
  { codigo: "200", nome: "Alíquota reduzida" },
  { codigo: "220", nome: "Alíquota fixa" },
  { codigo: "221", nome: "Alíquota fixa proporcional" },
  { codigo: "222", nome: "Redução de Base de Cálculo" },
  { codigo: "400", nome: "Isenção" },
  { codigo: "410", nome: "Imunidade e não incidência" },
  { codigo: "510", nome: "Diferimento" },
  { codigo: "515", nome: "Diferimento com redução de alíquota" },
  { codigo: "550", nome: "Suspensão" },
  { codigo: "620", nome: "Tributação Monofásica" },
  { codigo: "800", nome: "Transferência de crédito" },
  { codigo: "810", nome: "Ajuste de IBS na ZFM" },
  { codigo: "811", nome: "Ajustes" },
  { codigo: "820", nome: "Tributação em documento específico" },
  { codigo: "830", nome: "Exclusão da Base de Cálculo" },
];

export interface ClassTribIbsCbsItem { codigo: string; cst: string; nome: string; }
export const CLASS_TRIB_IBS_CBS: ClassTribIbsCbsItem[] = [
  { codigo: "000001", cst: "000", nome: "Situações tributadas integralmente pelo IBS e CBS." },
  { codigo: "000002", cst: "000", nome: "Exploração de via" },
  { codigo: "000003", cst: "000", nome: "Regime automotivo - projetos incentivados (art. 311)" },
  { codigo: "000004", cst: "000", nome: "Regime automotivo - projetos incentivados (art. 312)" },
  { codigo: "000005", cst: "000", nome: "Operação com EAC destinado à mistura com gasolina A, mas com saída do biocombustível com destinação diversa" },
  { codigo: "010001", cst: "010", nome: "Operações do FGTS não realizadas pela Caixa Econômica Federal" },
  { codigo: "010002", cst: "010", nome: "Operações do serviço financeiro" },
  { codigo: "011001", cst: "011", nome: "Planos de assistência funerária." },
  { codigo: "011002", cst: "011", nome: "Planos de assistência à saúde" },
  { codigo: "011003", cst: "011", nome: "Intermediação de planos de assistência à saúde" },
  { codigo: "011004", cst: "011", nome: "Concursos e prognósticos" },
  { codigo: "011005", cst: "011", nome: "Planos de assistência à saúde de animais domésticos" },
  { codigo: "200001", cst: "200", nome: "Serviços de transporte de bens até as zonas de processamento de exportação e bens exportados a partir das zonas de processamento de exportação" },
  { codigo: "200002", cst: "200", nome: "Fornecimento ou importação para produtor rural não contribuinte ou TAC" },
  { codigo: "200003", cst: "200", nome: "Vendas de produtos destinados à alimentação humana (Anexo I)" },
  { codigo: "200004", cst: "200", nome: "Fornecimento de dispositivos médicos (Anexo XII)" },
  { codigo: "200005", cst: "200", nome: "Fornecimento de dispositivos médicos para órgãos da administração pública e entidades de saúde imunes (Anexo IV)" },
  { codigo: "200006", cst: "200", nome: "Situação de emergência de saúde pública reconhecida pelo Poder público" },
  { codigo: "200007", cst: "200", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo XIII)" },
  { codigo: "200008", cst: "200", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência adquiridos por órgãos da administração pública (Anexo V)" },
  { codigo: "200009", cst: "200", nome: "Fornecimento dos medicamentos registrados na Anvisa" },
  { codigo: "200010", cst: "200", nome: "Fornecimento dos medicamentos registrados na Anvisa, adquiridos por órgãos da administração pública" },
  { codigo: "200011", cst: "200", nome: "Fornecimento das composições para nutrição enteral e parenteral quando adquiridas por órgãos da administração pública (Anexo VI)" },
  { codigo: "200012", cst: "200", nome: "Situação de emergência de saúde pública reconhecida pelo Poder público" },
  { codigo: "200013", cst: "200", nome: "Fornecimento de tampões higiênicos, absorventes higiênicos internos ou externos" },
  { codigo: "200014", cst: "200", nome: "Fornecimento dos produtos hortícolas, frutas e ovos (Anexo XV)" },
  { codigo: "200015", cst: "200", nome: "Venda de automóveis de passageiros de fabricação nacional adquiridos por motoristas profissionais ou pessoas com deficiência" },
  { codigo: "200016", cst: "200", nome: "Prestação de serviços de pesquisa e desenvolvimento por Instituição Científica, Tecnológica e de Inovação (ICT)" },
  { codigo: "200017", cst: "200", nome: "Operações relacionadas ao FGTS" },
  { codigo: "200018", cst: "200", nome: "Operações de resseguro e retrocessão" },
  { codigo: "200019", cst: "200", nome: "Importador dos serviços financeiros contribuinte" },
  { codigo: "200020", cst: "200", nome: "Operação praticada por sociedades cooperativas optantes por regime específico do IBS e CBS" },
  { codigo: "200021", cst: "200", nome: "Serviços de transporte público coletivo de passageiros ferroviário e hidroviário" },
  { codigo: "200022", cst: "200", nome: "Operação originada fora da ZFM que destine bem material industrializado a contribuinte estabelecido na ZFM" },
  { codigo: "200023", cst: "200", nome: "Operação realizada por indústria incentivada que destine bem material intermediário para outra indústria incentivada na ZFM" },
  { codigo: "200024", cst: "200", nome: "Operação originada fora das Áreas de Livre Comércio destinadas a contribuinte estabelecido nas Áreas de Livre Comércio" },
  { codigo: "200025", cst: "200", nome: "Fornecimento dos serviços de educação relacionados ao Programa Universidade para Todos (Prouni)" },
  { codigo: "200026", cst: "200", nome: "Locação de imóveis localizados nas zonas reabilitadas" },
  { codigo: "200027", cst: "200", nome: "Operações de locação, cessão onerosa e arrendamento de bens imóveis" },
  { codigo: "200028", cst: "200", nome: "Fornecimento dos serviços de educação (Anexo II)" },
  { codigo: "200029", cst: "200", nome: "Fornecimento dos serviços de saúde humana (Anexo III)" },
  { codigo: "200030", cst: "200", nome: "Venda dos dispositivos médicos (Anexo IV)" },
  { codigo: "200031", cst: "200", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo V)" },
  { codigo: "200032", cst: "200", nome: "Fornecimento dos medicamentos registrados na Anvisa ou produzidos por farmácias de manipulação, ressalvados os medicamentos sujeitos à alíquota zero" },
  { codigo: "200033", cst: "200", nome: "Fornecimento das composições para nutrição enteral e parenteral (Anexo VI)" },
  { codigo: "200034", cst: "200", nome: "Fornecimento dos alimentos destinados ao consumo humano (Anexo VII)" },
  { codigo: "200035", cst: "200", nome: "Fornecimento dos produtos de higiene pessoal e limpeza (Anexo VIII)" },
  { codigo: "200036", cst: "200", nome: "Fornecimento de produtos agropecuários, aquícolas, pesqueiros, florestais e extrativistas vegetais in natura" },
  { codigo: "200037", cst: "200", nome: "Fornecimento de serviços ambientais de conservação ou recuperação da vegetação nativa" },
  { codigo: "200038", cst: "200", nome: "Fornecimento dos insumos agropecuários e aquícolas (Anexo IX)" },
  { codigo: "200039", cst: "200", nome: "Fornecimento dos bens e serviços relacionados com produções nacionais artísticas, culturais, de eventos, jornalísticas e audiovisuais (Anexo X)" },
  { codigo: "200040", cst: "200", nome: "Fornecimento de serviços de comunicação institucional à administração pública" },
  { codigo: "200041", cst: "200", nome: "Fornecimento de serviço de educação desportiva (art. 141. I)" },
  { codigo: "200042", cst: "200", nome: "Fornecimento de serviço de gestão e exploração do desporto (art. 141. II)" },
  { codigo: "200043", cst: "200", nome: "Fornecimento à administração pública dos serviços e dos bens relativos à soberania (Anexo XI)" },
  { codigo: "200044", cst: "200", nome: "Operações e prestações de serviços de segurança da informação e segurança cibernética desenv por sociedade que tenha sócio brasileiro (Anexo XI)" },
  { codigo: "200045", cst: "200", nome: "Operações relacionadas a projetos de reabilitação urbana de zonas históricas e de áreas críticas de recuperação e reconversão urbanística" },
  { codigo: "200046", cst: "200", nome: "Operações com bens imóveis" },
  { codigo: "200047", cst: "200", nome: "Bares e Restaurantes" },
  { codigo: "200048", cst: "200", nome: "Hotelaria, Parques de Diversão e Parques Temáticos" },
  { codigo: "200049", cst: "200", nome: "Transporte coletivo de passageiros rodoviário, ferroviário e hidroviário" },
  { codigo: "200050", cst: "200", nome: "Serviços de transporte aéreo regional coletivo de passageiros ou de carga" },
  { codigo: "200051", cst: "200", nome: "Agências de Turismo" },
  { codigo: "200052", cst: "200", nome: "Prestação de serviços de profissões intelectuais" },
  { codigo: "200053", cst: "200", nome: "Fornecimento de medicamentos registrados na Anvisa, quando classificados como soros ou vacinas" },
  { codigo: "200054", cst: "200", nome: "Fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS" },
  { codigo: "220001", cst: "220", nome: "Incorporação imobiliária submetida ao regime especial de tributação" },
  { codigo: "220002", cst: "220", nome: "Incorporação imobiliária submetida ao regime especial de tributação" },
  { codigo: "220003", cst: "220", nome: "Alienação de imóvel decorrente de parcelamento do solo" },
  { codigo: "221001", cst: "221", nome: "Locação, cessão onerosa ou arrendamento de bem imóvel com alíquota sobre a receita bruta" },
  { codigo: "221002", cst: "221", nome: "Incorporação imobiliária submetida ao regime especial de tributação" },
  { codigo: "221003", cst: "221", nome: "Incorporação imobiliária submetida ao regime especial de tributação" },
  { codigo: "221004", cst: "221", nome: "Alienação de imóvel decorrente de parcelamento do solo" },
  { codigo: "222001", cst: "222", nome: "Transporte internacional de passageiros, caso os trechos de ida e volta sejam vendidos em conjunto" },
  { codigo: "400001", cst: "400", nome: "Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário" },
  { codigo: "400002", cst: "400", nome: "Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário com medição por quilômetro rodado" },
  { codigo: "410001", cst: "410", nome: "Fornecimento de bonificações quando constem no documento fiscal e que não dependam de evento posterior" },
  { codigo: "410002", cst: "410", nome: "Transferências entre estabelecimentos pertencentes ao mesmo contribuinte" },
  { codigo: "410003", cst: "410", nome: "Doações sem contraprestação em benefício do doador" },
  { codigo: "410004", cst: "410", nome: "Exportações de bens e serviços" },
  { codigo: "410005", cst: "410", nome: "Fornecimentos realizados pela União, pelos Estados, pelo Distrito Federal e pelos Municípios" },
  { codigo: "410006", cst: "410", nome: "Fornecimentos realizados por entidades religiosas e templos de qualquer culto" },
  { codigo: "410007", cst: "410", nome: "Fornecimentos realizados por partidos políticos, entidades sindicais e instituições de educação e de assistência social" },
  { codigo: "410008", cst: "410", nome: "Fornecimentos de livros, jornais, periódicos e do papel destinado a sua impressão" },
  { codigo: "410009", cst: "410", nome: "Fornecimentos de fonogramas e videofonogramas musicais produzidos no Brasil" },
  { codigo: "410010", cst: "410", nome: "Fornecimentos de serviço de comunicação nas modalidades de radiodifusão sonora e de sons e imagens de recepção livre e gratuita" },
  { codigo: "410011", cst: "410", nome: "Fornecimentos de ouro, quando definido em lei como ativo financeiro ou instrumento cambial" },
  { codigo: "410012", cst: "410", nome: "Fornecimento de condomínio edilício não optante pelo regime regular" },
  { codigo: "410013", cst: "410", nome: "Exportações de combustíveis" },
  { codigo: "410014", cst: "410", nome: "Fornecimento de produtor rural não contribuinte" },
  { codigo: "410015", cst: "410", nome: "Fornecimento por transportador autônomo não contribuinte" },
  { codigo: "410016", cst: "410", nome: "Fornecimento ou aquisição de resíduos sólidos" },
  { codigo: "410017", cst: "410", nome: "Aquisição de bem móvel com crédito presumido sob condição de revenda realizada" },
  { codigo: "410018", cst: "410", nome: "Operações relacionadas aos fundos garantidores e executores de políticas públicas" },
  { codigo: "410019", cst: "410", nome: "Exclusão da gorjeta na base de cálculo no fornecimento de alimentação" },
  { codigo: "410020", cst: "410", nome: "Exclusão do valor de intermediação na base de cálculo no fornecimento de alimentação" },
  { codigo: "410021", cst: "410", nome: "Contribuição de que trata o art. 149-A da Constituição Federal" },
  { codigo: "410022", cst: "410", nome: "Consolidação da propriedade do bem pelo credor" },
  { codigo: "410023", cst: "410", nome: "Alienação de bens móveis ou imóveis que tenham sido objeto de garantia em que o prestador da garantia não seja contribuinte" },
  { codigo: "410024", cst: "410", nome: "Consolidação da propriedade do bem pelo grupo de consórcio" },
  { codigo: "410025", cst: "410", nome: "Alienação de bem que tenha sido objeto de garantia em que o prestador da garantia não seja contribuinte" },
  { codigo: "410026", cst: "410", nome: "Doação com anulação de crédito" },
  { codigo: "410027", cst: "410", nome: "Exportação de serviço ou de bem imaterial" },
  { codigo: "410028", cst: "410", nome: "Operações com bens imóveis realizadas por pessoas físicas não consideradas contribuintes" },
  { codigo: "410029", cst: "410", nome: "Operações acobertadas somente pelo ICMS" },
  { codigo: "410030", cst: "410", nome: "Estorno de crédito por perecimento, deteriorização, roubo, furto ou extravio." },
  { codigo: "410031", cst: "410", nome: "Fornecimento em período anterior ao início de vigência de incidências de CBS e IBS" },
  { codigo: "410032", cst: "410", nome: "Tributos incidentes na operação que não integram a base de cálculo do IBS e da CBS" },
  { codigo: "410033", cst: "410", nome: "Operações de Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro)" },
  { codigo: "410034", cst: "410", nome: "Operações de fundos de investimento" },
  { codigo: "410035", cst: "410", nome: "Fornecimento realizado por nanoempreendedor" },
  { codigo: "410036", cst: "410", nome: "Descontos incondicionais" },
  { codigo: "410037", cst: "410", nome: "Importação de bens materiais sem incidência de IBS e CBS" },
  { codigo: "410999", cst: "410", nome: "Operações não onerosas sem previsão de tributação, não especificadas anteriormente" },
  { codigo: "510001", cst: "510", nome: "Operações, sujeitas a diferimento, com energia elétrica, relativas à importação, geração, comercialização, distribuição e transmissão" },
  { codigo: "515001", cst: "515", nome: "Operações, sujeitas a diferimento, com insumos agropecuários e aquícolas (Anexo IX)" },
  { codigo: "550001", cst: "550", nome: "Exportações de bens materiais" },
  { codigo: "550002", cst: "550", nome: "Regime de Trânsito" },
  { codigo: "550003", cst: "550", nome: "Regimes de Depósito (art. 85)" },
  { codigo: "550004", cst: "550", nome: "Regimes de Depósito (art. 87)" },
  { codigo: "550005", cst: "550", nome: "Regimes de Depósito (art. 87, Parágrafo único)" },
  { codigo: "550006", cst: "550", nome: "Regimes de Permanência Temporária" },
  { codigo: "550007", cst: "550", nome: "Regimes de Aperfeiçoamento" },
  { codigo: "550008", cst: "550", nome: "Importação de bens para o Regime de Repetro-Temporário" },
  { codigo: "550009", cst: "550", nome: "GNL-Temporário" },
  { codigo: "550010", cst: "550", nome: "Repetro-Permanente" },
  { codigo: "550011", cst: "550", nome: "Repetro-Industrialização" },
  { codigo: "550012", cst: "550", nome: "Repetro-Nacional" },
  { codigo: "550013", cst: "550", nome: "Repetro-Entreposto" },
  { codigo: "550014", cst: "550", nome: "Zona de Processamento de Exportação" },
  { codigo: "550015", cst: "550", nome: "Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária" },
  { codigo: "550016", cst: "550", nome: "Regime Especial de Incentivos para o Desenvolvimento da Infraestrutura" },
  { codigo: "550017", cst: "550", nome: "Regime Tributário para Incentivo à Atividade Econômica Naval" },
  { codigo: "550018", cst: "550", nome: "Desoneração da aquisição de bens de capital" },
  { codigo: "550019", cst: "550", nome: "Importação de bem material por indústria incentivada para utilização na ZFM" },
  { codigo: "550020", cst: "550", nome: "Áreas de livre comércio" },
  { codigo: "550021", cst: "550", nome: "Industrialização destinada a exportações" },
  { codigo: "550022", cst: "550", nome: "Regime Especial de Incentivos para a Produção de Hidrogênio de Baixa Emissão de Carbono (Rehidro)" },
  { codigo: "550023", cst: "550", nome: "Operações com hidrocarbonetos líquidos derivados de petróleo não combustíveis ou de gás natural, inclusive nafta" },
  { codigo: "550024", cst: "550", nome: "Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, II)" },
  { codigo: "550025", cst: "550", nome: "Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, III)" },
  { codigo: "620001", cst: "620", nome: "Tributação monofásica sobre combustíveis" },
  { codigo: "620002", cst: "620", nome: "Tributação monofásica com responsabilidade pela retenção sobre combustíveis" },
  { codigo: "620003", cst: "620", nome: "Tributação monofásica com responsabilidade de retenção de tributos por terceiros" },
  { codigo: "620004", cst: "620", nome: "Tributação monofásica sobre mistura de EAC com gasolina A em percentual superior ao obrigatório" },
  { codigo: "620005", cst: "620", nome: "Tributação monofásica sobre mistura de EAC com gasolina A em percentual inferior ao obrigatório" },
  { codigo: "620006", cst: "620", nome: "Tributação monofásica sobre combustíveis cobrada anteriormente" },
  { codigo: "620007", cst: "620", nome: "Perecimento, deteriorização, roubo, furto ou extravio no regime monofásico" },
  { codigo: "800001", cst: "800", nome: "Fusão, cisão ou incorporação" },
  { codigo: "800002", cst: "800", nome: "Transferência de crédito do associado, inclusive as cooperativas singulares" },
  { codigo: "810001", cst: "810", nome: "Crédito presumido sobre o valor apurado nos fornecimentos a partir da ZFM" },
  { codigo: "811001", cst: "811", nome: "Anulação de Crédito por Saídas Imunes/Isentas" },
  { codigo: "811002", cst: "811", nome: "Débitos de notas fiscais não processadas na apuração" },
  { codigo: "811003", cst: "811", nome: "Desenquadramento do Simples Nacional" },
  { codigo: "820001", cst: "820", nome: "Documento com informações de fornecimento de serviços de planos de assistência à saúde elencados no art. 234 da Lei Complementar nº214, de 2025" },
  { codigo: "820002", cst: "820", nome: "Documento com informações de fornecimento de serviços de planos de assinstência funerária" },
  { codigo: "820003", cst: "820", nome: "Documento com informações de fornecimento de serviços de planos de assistência à saúde de animais domésticos" },
  { codigo: "820004", cst: "820", nome: "Documento com informações de prestação de serviços de consursos de prognósticos" },
  { codigo: "820005", cst: "820", nome: "Documento com informações de alienação de bens imóveis" },
  { codigo: "820006", cst: "820", nome: "Documento com informações de fornecimento de serviços de exploração de via" },
  { codigo: "820007", cst: "820", nome: "Documento com informações de fornecimento de serviços financeiros" },
  { codigo: "820008", cst: "820", nome: "Documento com informações de fornecimento de serviço continuado, mas com tributação realizada em fatura anterior" },
  { codigo: "820009", cst: "820", nome: "Cobrança relativa a fornecimentos declarados em outro documento" },
  { codigo: "830001", cst: "830", nome: "Documento com exclusão da BC da CBS e do IBS de energia elétrica fornecida pela distribuidora à UC" },
];

export interface IndOpIbsCbsItem { codigo: string; operacao: string; caracteristica: string; }
export const IND_OP_IBS_CBS: IndOpIbsCbsItem[] = [
  { codigo: "010101", operacao: "Bem Móvel Material", caracteristica: "Presencial, com retirada no estabelecimento do fornecedor" },
  { codigo: "010102", operacao: "Bem Móvel Material", caracteristica: "Presencial, com retirada fora do estabelecimento do fornecedor" },
  { codigo: "010103", operacao: "Bem Móvel Material", caracteristica: "Não presencial, com entrega ou disponibilização em endereço fornecido" },
  { codigo: "010106", operacao: "Bem Móvel Material", caracteristica: "Locação de bem móvel material em aquisições realizadas de forma centralizada por contribuinte sujeito ao regime regular do IBS e da CBS que possui mais de um estabelecimento e que não estejam sujeitas a vedação à apropriação de créditos" },
  { codigo: "020101", operacao: "Operação com bem imóvel, bem imaterial, inclusive direito, relacionada a bem imóvel", caracteristica: "Realização de operações com bem imóvel, bem imaterial, inclusive direito, relacionado a bem imóvel" },
  { codigo: "020201", operacao: "Serviço prestado fisicamente sobre bem imóvel", caracteristica: "Execução de serviços diversos prestados fisicamente sobre bem imóvel" },
  { codigo: "020202", operacao: "Serviço prestado fisicamente sobre bem imóvel", caracteristica: "Execução de serviços sobre Bens Imóveis de Características Especiais (BICE)" },
  { codigo: "020301", operacao: "Serviço de administração e intermediação de bem imóvel", caracteristica: "Execução dos serviços de administração e intermediação de bens imóveis" },
  { codigo: "020401", operacao: "Serviços de locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza", caracteristica: "Execução de serviços sobre Bens Imóveis de Características Especiais (BICE)" },
  { codigo: "030101", operacao: "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física", caracteristica: "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física" },
  { codigo: "030102", operacao: "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física", caracteristica: "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física" },
  { codigo: "040101", operacao: "Serviço de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres", caracteristica: "Execução de serviços de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres" },
  { codigo: "050101", operacao: "Serviço prestado fisicamente sobre bem móvel material", caracteristica: "Execução de serviços diversos prestados fisicamente sobre bem móvel material" },
  { codigo: "050102", operacao: "Serviço prestado fisicamente sobre bem móvel material", caracteristica: "Execução de serviços diversos prestados fisicamente sobre bem móvel material" },
  { codigo: "050201", operacao: "Serviços portuários", caracteristica: "Execução de serviços portuários" },
  { codigo: "060101", operacao: "Serviço de transporte de passageiros", caracteristica: "Execução de serviços de transporte de passageiros" },
  { codigo: "070101", operacao: "Serviço de transporte de carga", caracteristica: "Execução de serviço de transporte de carga" },
  { codigo: "070102", operacao: "Serviço de transporte de carga", caracteristica: "Execução de serviço de transporte de carga" },
  { codigo: "100101", operacao: "Cessão de espaço para prestação de serviços publicitários, em operações onerosas", caracteristica: "Realização de operações de cessão de espaço para prestação de serviços publicitários" },
  { codigo: "100102", operacao: "Cessão de espaço para prestação de serviços publicitários, em operações onerosas", caracteristica: "Realização de operações de cessão de espaço para prestação de serviços publicitários" },
  { codigo: "100201", operacao: "Cessão de espaço para prestação de serviços publicitários, em operações não onerosas", caracteristica: "Realização de operações de cessão de espaço para prestação de serviços publicitários" },
  { codigo: "100301", operacao: "Demais serviços, em operações onerosas", caracteristica: "Execução dos demais serviços em operações não especificadas em outros indicadores ou, nos serviços de que trata o inc. III do art. 11, esses sejam, ainda que parcialmente, prestados à distância" },
  { codigo: "100302", operacao: "Demais serviços, em operações onerosas", caracteristica: "Execução dos demais serviços em operações não especificadas em outros indicadores ou, nos serviços de que trata o inc. III do art. 11, esses sejam, ainda que parcialmente, prestados à distância" },
  { codigo: "100401", operacao: "Demais serviços, em operações não onerosas", caracteristica: "Execução dos demais serviços em operações não especificadas em outros indicadores ou, nos serviços de que tratam o inc. III, estes sejam, ainda que parcialmente, prestados à distância" },
];
